services:

    mdiyakov_doctrine_solr.config.config:
        class: Mdiyakov\DoctrineSolrBundle\Config\Config
        arguments:
            - []    #see MdiyakovDoctrineSolrExtension for arguments details
            - []    #see MdiyakovDoctrineSolrExtensionfor arguments details
            - []    #see MdiyakovDoctrineSolrExtensionfor arguments details
            - []    #see MdiyakovDoctrineSolrExtensionfor arguments details

    mdiyakov_doctrine_solr.event_listener.doctrine_entity:
        class: Mdiyakov\DoctrineSolrBundle\EventListener\DoctrineEntityListener
        arguments:
            - '@mdiyakov_doctrine_solr.manager.index_process_manager'

    mdiyakov_doctrine_solr.manager.index_process_manager:
      class: Mdiyakov\DoctrineSolrBundle\Manager\IndexProcessManager
      arguments:
          - '@mdiyakov_doctrine_solr.indexer.builder'
          - '@mdiyakov_doctrine_solr.filter.validator'

    mdiyakov_doctrine_solr.config.validator:
        class: Mdiyakov\DoctrineSolrBundle\Config\ConfigValidator
        public: false

    mdiyakov_doctrine_solr.indexer.builder:
        class: Mdiyakov\DoctrineSolrBundle\Indexer\IndexerBuilder
        public: false
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@mdiyakov_doctrine_solr.query.update_builder'

    mdiyakov_doctrine_solr.filter.validator:
        class: Mdiyakov\DoctrineSolrBundle\Filter\FilterValidator
        public: false
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'

    mdiyakov_doctrine_solr.command.index_entities:
        class: Mdiyakov\DoctrineSolrBundle\Command\IndexEntitiesCommand
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@mdiyakov_doctrine_solr.manager.index_process_manager'
            - '@doctrine'
        tags:
            - { name: console.command }

    mdiyakov_doctrine_solr.command.clear_index:
        class: Mdiyakov\DoctrineSolrBundle\Command\ClearIndexCommand
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@mdiyakov_doctrine_solr.query.update_builder'
            - '@doctrine'
        tags:
            - { name: console.command }

    mdiyakov_doctrine_solr.query.hydrator.builder:
        class: Mdiyakov\DoctrineSolrBundle\Query\Hydrator\HydratorBuilder
        public: false
        arguments:
            - '@doctrine'
            - '@mdiyakov_doctrine_solr.config.config'

    mdiyakov_doctrine_solr.query.select_builder:
        class: Mdiyakov\DoctrineSolrBundle\Query\SelectQueryBuilder
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@solarium.client_registry'
            - '@mdiyakov_doctrine_solr.query.hydrator.builder'

    mdiyakov_doctrine_solr.query.update_builder:
        class: Mdiyakov\DoctrineSolrBundle\Query\UpdateQueryBuilder
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@solarium.client_registry'

    mdiyakov_doctrine_solr.query.suggester_builder:
        class: Mdiyakov\DoctrineSolrBundle\Query\SuggestQueryBuilder
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@solarium.client_registry'

    mdiyakov_doctrine_solr.manager.finder:
        class: Mdiyakov\DoctrineSolrBundle\Manager\FinderManager
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@mdiyakov_doctrine_solr.query.select_builder'

    mdiyakov_doctrine_solr.manager.suggester:
        class: Mdiyakov\DoctrineSolrBundle\Manager\SuggesterManager
        arguments:
            - '@mdiyakov_doctrine_solr.config.config'
            - '@mdiyakov_doctrine_solr.query.suggester_builder'

    mdiyakov_doctrine_solr.manager.entity_manager:
        class: Mdiyakov\DoctrineSolrBundle\Manager\EntityManager
        arguments:
            - '@mdiyakov_doctrine_solr.manager.index_process_manager'
            - '@doctrine'

    ds.entity_manager:
        alias: mdiyakov_doctrine_solr.manager.entity_manager

    ds.suggester:
        alias: mdiyakov_doctrine_solr.manager.suggester

    ds.finder:
        alias: mdiyakov_doctrine_solr.manager.finder