language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=2.8.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

install: travis_retry composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -c phpunit.xml.dist