language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
  - SYMFONY_VERSION=2.7.*
  - SYMFONY_VERSION=3.0.*
  - SYMFONY_VERSION=3.1.*

matrix:
  exclude:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.4
      env: SYMFONY_VERSION=3.0.*
    - php: 5.4
      env: SYMFONY_VERSION=3.1.*


before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --update-with-all-dependencies "symfony/framework-bundle:$SYMFONY_VERSION"; fi

install: travis_retry composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -c phpunit.xml.dist