language: php
php:
  - 5.4
  - 5.5
  - 5.6

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""
  - SYMFONY_VERSION=2.7.*

before_script:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --update-with-all-dependencies "symfony/framework-bundle:$SYMFONY_VERSION"; fi

install: travis_retry composer update $COMPOSER_FLAGS

script: ./vendor/bin/phpunit -c phpunit.xml.dist